### PR TITLE
Fixed debug log message

### LINKED ISSUE #32: UCF_FAQ_Common::get_related_faqs_by_topic() throws warnings when no related FAQs are set
`Warning: array_merge(): Argument #2 is not an array in /common/ucf-faq-list-common.php on line 214`

`Warning: array_filter() expects parameter 1 to be array, null given in /common/ucf-faq-list-common.php on line 223 `

https://github.com/UCF/UCF-FAQ-CPT/blob/master/common/ucf-faq-list-common.php#L212-L223

Need to ensure `$related` actually returns an array before attempting to merge it into `$retval`.

### PR DESCRIPTION
**Pull request by rjucf**
Fixes #32

### CODE REVIEW

File: common/ucf-faq-list-common.php [hunk 1]
```diff
@@ -211,7 +211,9 @@ public static function get_related_faqs_by_topic( $topics, $excluded_faqs ) {
 
 			foreach( $topics as $topic ) {
 				$related = get_field( 'related_faqs', "topic_{$topic->term_id}" );
-				$retval = array_merge( $retval, $related );
+				if( $related ) {
```
Comment (jmbarne3) [inline common/ucf-faq-list-common.php]: You're probably going to want to make sure $related is an array before trying to merge it with another array as well. `is_array` will do the trick.
